--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync
deploy:
  default:
    dst: "server:basedir/subdir"
    options: ['-ave ssh', '--exclude=.DS_Store', '--exclude=*~']

# domain to which this site is deployed
base_url: http://some-server.com

google_analytics:
  domain: some-server.com
  site_id: UA-123456789-1

# currently used by logo
site_name: mynock

# number of full featured posts to display on front
featured_count: 1

# number of excerpted posts to display on front
excerpt_count: 5

# number of other articles to reference at bottom of each article
other_articles_max: 3

# DISQUS Site Shortname. Comment out to disable.
disqus_shortname: mynock

